;window.replace=function(){return ''};(function(a){function b(a,b){var d=(/^\w+\:\/\//);((/^\/\/\/?/).test(a)?a=location.protocol+a:!d.test(a)&&"/"!=a.charAt(0)&&(a=(b||"")+a));return (d.test(a)?a:("/"==a.charAt(0)?x:y)+a)}function c(a,b){for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b}function e(a,b,d,c){a.onload=a.onreadystatechange=function(){a.readyState&&"complete"!=a.readyState&&"loaded"!=a.readyState||b[d]||(a.onload=a.onreadystatechange=null,c())};a.onerror=function(){try{var a=this.src;cError.logError&&cError.logError(["error",
"[Error loading script - status "+d+"]",0,a],"scriptload-error","normal")}catch(b){}}}function k(a){a.ready=a.finished=!0;for(var b=0;b<a.finished_listeners.length;b++)a.finished_listeners[b]();a.ready_listeners=[];a.finished_listeners=[]}function v(a,b,d,c,k){setTimeout(function(){var f,l=b.real_src,h;if("item"in m){if(!m[0]){setTimeout(arguments.callee,25);return}m=m[0]}f=document.createElement("script");b.type&&(f.type=b.type);b.charset&&(f.charset=b.charset);(k?(u?(a[p]&&n("start script preload: "+
l),d.elem=f,(z?(f.preload=!0,f.onpreload=c):f.onreadystatechange=function(){"loaded"==f.readyState&&c()}),f.src=l):(k&&0==l.indexOf(x)&&a[A]?(h=new XMLHttpRequest,a[p]&&n("start script preload (xhr): "+l),h.onreadystatechange=function(){4==h.readyState&&(h.onreadystatechange=function(){},d.text=h.responseText+"\n//@ sourceURL="+l,c())},h.open("GET",l),h.send()):(a[p]&&n("start script preload (cache): "+l),f.type="text/cache-script",e(f,d,"ready",function(){m.removeChild(f);c()}),f.src=l,m.insertBefore(f,
m.firstChild)))):((B?(a[p]&&n("start script load (ordered async): "+l),f.async=!1):a[p]&&n("start script load: "+l)),e(f,d,"finished",c),f.src=l,m.insertBefore(f,m.firstChild)))},0)}function s(){function H(a,b,c){function f(){null!=g&&(g=null,k(c))}var g;l[b.src].finished||(a[w]||(l[b.src].finished=!0),g=c.elem||document.createElement("script"),b.type&&(g.type=b.type),b.charset&&(g.charset=b.charset),e(g,c,"finished",f),(c.elem?c.elem=null:(c.text?(g.onload=g.onreadystatechange=null,g.text=c.text):g.src=
b.real_src)),m.insertBefore(g,m.firstChild),c.text&&f())}function I(a,c,f,d){var g,t,e=function(){c.ready_cb(c,function(){H(a,c,g)})},h=function(){c.finished_cb(c,f)};c.src=b(c.src,a[C]);c.real_src=c.src+(a[D]?((/\?.*$/).test(c.src)?"&_":"?_")+~~(1E9*Math.random())+"=":"");l[c.src]||(l[c.src]={items:[],finished:!1});t=l[c.src].items;(a[w]||0==t.length?(g=t[t.length]={ready:!1,finished:!1,ready_listeners:[e],finished_listeners:[h]},v(a,c,g,(d?function(){g.ready=!0;for(var a=0;a<g.ready_listeners.length;a++)g.ready_listeners[a]();
g.ready_listeners=[]}:function(){k(g)}),d)):(g=t[0],(g.finished?h():g.finished_listeners.push(h))))}function d(){function a(b,c){g[p]&&n("script preload finished: "+b.real_src);b.ready=!0;b.exec_trigger=c;f()}function b(a,c){g[p]&&n("script execution finished: "+a.real_src);a.ready=a.finished=!0;a.exec_trigger=null;for(var d=0;d<c.scripts.length;d++)if(!c.scripts[d].finished)return;c.finished=!0;f()}function f(){for(;e<h.length;)if("[object Function]"==Object.prototype.toString.call(h[e])){g[p]&&n("$LAB.wait() executing: "+
h[e]);try{h[e++]()}catch(a){g[p]&&E("$LAB.wait() error caught: ",a)}}else{if(!h[e].finished){for(var b=h[e],c=!1,d=0;d<b.scripts.length;d++)b.scripts[d].ready&&b.scripts[d].exec_trigger&&(c=!0,b.scripts[d].exec_trigger(),b.scripts[d].exec_trigger=null);if(c)continue;break}e++}e==h.length&&(k=l=!1)}var d,g=c(q,{}),h=[],e=0,l=!1,k;d={script:function(){for(var f=0;f<arguments.length;f++){var e=arguments[f],m=arguments[f],p=void 0;"[object Array]"==Object.prototype.toString.call(e)||(m=[e]);for(var n=
0;n<m.length;n++){if(!k||!k.scripts)h.push(k={scripts:[],finished:!0});e=m[n];"[object Function]"==Object.prototype.toString.call(e)&&(e=e());e&&("[object Array]"==Object.prototype.toString.call(e)?(p=[].slice.call(e),p.unshift(n,1),[].splice.apply(m,p),n--):("string"==typeof e&&(e={src:e}),e=c(e,{ready:!1,ready_cb:a,finished:!1,finished_cb:b}),k.finished=!1,k.scripts.push(e),I(g,e,k,r&&l),l=!0,g[F]&&d.wait()))}}return d},padScript:function(){var a=(navigator.userAgent.match((/(iPad).*OS\s([\d_]+)/))?
!0:!1),b=arguments;a||(b[0]="");return d.script.apply(null,b)},miniScript:function(){return d.script.apply(null,arguments)},wait:function(){if(0<arguments.length){for(var a=0;a<arguments.length;a++)h.push(arguments[a]);k=h[h.length-1]}else k=!1;f();return d}};return{script:d.script,wait:d.wait,padScript:d.padScript,miniScript:d.miniScript,setOptions:function(a){c(a,g);return d}}}var q={},r=u||J,f=[],l={},h;q[A]=!1;q[F]=!1;q[w]=!1;q[D]=!1;q[p]=!1;q[C]="";return h={setGlobalDefaults:function(a){c(a,
q);return h},setOptions:function(){return d().setOptions.apply(null,arguments)},script:function(){return d().script.apply(null,arguments)},padScript:function(){return d().padScript.apply(null,arguments)},miniScript:function(){return d().miniScript.apply(null,arguments)},wait:function(){return d().wait.apply(null,arguments)},queueScript:function(){f[f.length]={type:"script",args:[].slice.call(arguments)};return h},queueWait:function(){f[f.length]={type:"wait",args:[].slice.call(arguments)};return h},
runQueue:function(){for(var a=h,b=f.length,c;0<=--b;)c=f.shift(),a=a[c.type].apply(null,c.args);return a},noConflict:function(){a.$LAB=G;return h},sandbox:function(){return s()}}}var G=a.$LAB,A="UseLocalXHR",F="AlwaysPreserveOrder",w="AllowDuplicates",D="CacheBust",p="Debug",C="BasePath",y=(/^[^?#]*\//).exec(location.href)[0],x=(/^\w+\:\/\/\/?[^\/]+/).exec(y)[0],m=document.head||document.getElementsByTagName("head"),K=a.opera&&"[object Opera]"==Object.prototype.toString.call(a.opera)||"MozAppearance"in
document.documentElement.style,n=function(){},E=n,r=document.createElement("script"),z="boolean"==typeof r.preload,u=z||r.readyState&&"uninitialized"==r.readyState,B=!u&&!0===r.async,J=!u&&!B&&!K;a.console&&a.console.log&&(a.console.error||(a.console.error=a.console.log),n=function(b){a.console.log(b)},E=function(b,c){a.console.error(b,c)});a.$LAB=s();(function(a,b,c){null==document.readyState&&document[a]&&(document.readyState="loading",document[a](b,c=function(){document.removeEventListener(b,c,
!1);document.readyState="complete"},!1))})("addEventListener","DOMContentLoaded")})(this);"undefined"==typeof window.__uidc_init&&(window.__uidc_init=1*new Date);
(function(){function a(){try{document.documentElement.doScroll("left"),$LAB.isReady=!0}catch(b){setTimeout(a,1)}}if(document.addEventListener)document.addEventListener("DOMContentLoaded",function(){$LAB.isReady=!0},!1),window.addEventListener("load",function(){$LAB.isLoaded=!0},!1);else if(document.attachEvent){window.attachEvent("onload",function(){$LAB.isLoaded=!0});var b;try{b=null==window.frameElement}catch(c){}document.documentElement.doScroll&&b&&setTimeout(a,1)}})();
Array.prototype.isSame=function(a){if(this.length!=a.length)return!1;for(var b=0,c=this.length;b<c;b++)if((this[b]||"").toString()!=(a[b]||"").toString())return!1;return!0};$LAB.errorQueue=[];$errorCollection=[];$ubtErrorQueue=[];
var cError={init:function(){cError.flag=!1;cError.spliter=String.fromCharCode(12);cError.setTimer()},checkIsSent:function(a){for(var b=0,c=$errorCollection.length;b<c;b++)if($errorCollection[b].isSame(a))return!0;$errorCollection.push(a);return!1},setTimer:function(){setInterval(function(){cError.fetchError(!1)},500)}};cError.throwError=new Function("err","throw err;");
cError.fetchError=function(a){if(cError.flag==a)if(0!=$LAB.errorQueue.length){cError.flag=!0;var b=$LAB.errorQueue[0];setTimeout(function(){var a=((/msie (\d+)/i).test(navigator.userAgent)?Error(b.number||0,b.msg+cError.spliter):Error(b.msg+cError.spliter,b.file||"",b.line||0));cError.throwError(a)})}else cError.flag=!1};
cError.logError=function(a,b,c){try{if(0!=arguments.length&&!cError.checkIsSent(a)&&(/^http:\/\//).test(document.URL)){for(var e=a.concat([new Date-window.__uidc_init,document.getElementById("page_id")&&document.getElementById("page_id").value,window.UIMonitor2&&window.UIMonitor2.bi&&window.UIMonitor2.bi.pageview_id||"",document.URL,b||"",c||"","cQuery_121128"]),k=0,v=e.length;k<v;k++)e[k]=(""+e[k]).slice().replace((/,/g),"_");(new (Image)).src="http://ubtcollector.c-ctrip.com/?ac=error&data="+encodeURIComponent(e.join(","))+
"&rid="+Math.random();var s={version:"1.0",message:a[1],line:a[2],file:a[3],category:b,framework:"cQuery_110421",time:new Date-window.__uidc_init,repeat:1};("undefined"!=typeof $_bf&&"undefined"!=typeof $_bf.loaded?$_bf.trackError(s,function(){return!0}):$ubtErrorQueue.push(s))}}catch(G){}};cError.init();
window.onerror=function(){try{if(cQuery&&cQuery.config("allowDebug"))throw Error(arguments);if(cError.flag&&arguments[0].slice(-1)==cError.spliter){var a=$LAB.errorQueue.shift();cError.logError(["error",a.msg,a.line,a.file],"outer-error","normal");cError.fetchError(!0)}else cError.logError(["error",arguments[0],arguments[2],arguments[1]],"inner-error","normal")}catch(b){}};
function logTimer(){var a=document.getElementById("page_id");if(a)var b=(window.__uidc_init?new Date-window.__uidc_init:-1),c=setInterval(function(){window.UIMonitor2&&window.UIMonitor2.trackLog&&(clearInterval(c),window.UIMonitor2.trackLog(a.value,"jsfiles_complete_load",b))},30)}
(function(){for(var a=document.getElementsByTagName("script")||[],b=(/_bfa\.min\.js/i),c=0;c<a.length;c++)if(b.test(a[c].src))return;if(!window.$_bf){a=new Date;b="?v="+a.getFullYear()+a.getMonth()+"_"+a.getDate()+".js";a=document.createElement("script");a.type="text/javascript";a.charset="utf-8";a.async=!0;try{var e="https:"==document.location.protocol}catch(k){e="https:"==document.URL.match((/[^:]+/))+":"}a.src=(e?"https://s.c-ctrip.com/_bfa.min.js"+b:"http://webresource.c-ctrip.com/code/ubt/_bfa.min.js"+
b);e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})();(function(){if("undefined"!=typeof $_bf&&"undefined"!=typeof $_bf.loaded){for(var a=0,b=$ubtErrorQueue.length;a<b;a++)$_bf.trackError($ubtErrorQueue[a],function(){return!0});return!1}setTimeout(arguments.callee,250)})();